version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "ads"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
  nginx:
    image: ghcr.io/bizinmitya/front-react-avito:v1.21
    ports:
      - "3000:3000"
    container_name: front-react